"""Add missing objective columns

Revision ID: 5a8993416980
Revises: 86e6c782af98
Create Date: 2026-01-02 02:57:09.049523

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a8993416980"
down_revision: str | Sequence[str] | None = "86e6c782af98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("objectives", sa.Column("target_minutes", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("objectives", sa.Column("metric", sa.String(), nullable=False, server_default="minutes"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives", "metric")
    op.drop_column("objectives", "target_minutes")
    # ### end Alembic commands ###
